### PR TITLE
Fixes Nest Box, Adds Unique Shields, Assorted Bugs

### PR DESCRIPTION
**Pull request by Therighthon**

### CODE REVIEW

**Comment by alcatrazEscapee** [comment]
Most of them I think are great, I'm seeing some issues with some shields:
 - Black bronze shield has no texture
 - Steel shield is missing a model + texture
 - I'm very much not a fan of how the iron shield has a higher res texture than any other item in the inventory. This should be changed to a normal 16x16 texture.
 - Red steel shield is 1 px to large - it escapes the bottom of the slot, which looks bad.

**Comment by Therighthon** [comment]
Alright, fixed the listed issues. Let me know what you think about the iron shield as is. Alternative would be rotating them all like the vanilla shield, which looks bad on the round shields, or remaking the model as it is currently not possible from an item model standpoint to have the inventory use a different model than the hand/ground.

**Comment by alcatrazEscapee** [comment]
Can you reformat to fix all the merge conflicts please and thank you

**Comment by Therighthon** [comment]
Conflicts seem to be fixed, let me know if I screwed something up during the process because I am still gitting the hang of this

**Pull request closed without merging**
