### PR TITLE
Update zh_cn.lang

### PR DESCRIPTION
**Pull request by HeartyYF**

### CODE REVIEW

**Comment by HeartyYF** [comment]
Can anyone explain "Should living in a chunk block hostile mob spawning over time?" to me plz
I tried to look up the codes but I still got confused as the note "Added spawn protection. Same as classic, 1 hr = +6 hrs of spawn protection, requires 24 hrs to prevent hostile spawns."

**Comment by HeartyYF** [comment]
> The weight for loose rocks and sticks regeneration in the world.

Is this “weight” referring to weighted calculation or the number they regen?

**Comment by HeartyYF** [comment]
Also what is "Vinegar Milk"?

**Comment by alcatrazEscapee** [comment]
> Should living in a chunk block hostile mob spawning over time?

See <https://1710-wiki.terrafirmacraft.com/Protection_Meter#Spawn_Protection>

> The weight for loose rocks and sticks regeneration in the world.

Multiplier for how much they regenerate.

> Vinegar Milk

Exactly what it says: take milk, add vinegar

**Comment by HeartyYF** [comment]
OK

**Pull request closed without merging**
